"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

"""

sequence = [1, 2]

for i,n in enumerate(sequence):
    new_number = n + sequence[ i + 1 ]
    if new_number > 4000000:
        break
    sequence.append( new_number )

answer = 0
for n in sequence:
    if n % 2 == 0:
        answer = answer + n

print( answer )

